{% set major = "1.42" %}
{% set patch = "4" %}
{% set version = major + "." + patch %}

package:
  name: pango
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/{{ major }}/pango-{{ version }}.tar.xz
  sha256: 1d2b74cd63e8bd41961f2f8d952355aa0f9be6002b52c8aa7699d9f5da597c9d
  patches:
    # pc file patch should not be needed for version 1.43+
    - windows_fix_libm_in_pc_file.patch  # [win]

build:
  number: 5
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - {{ compiler('cxx') }}

requirements:
  build:
    - make  # [not win]
    # see https://github.com/conda-forge/meson-feedstock/issues/30
    - meson 0.53.2  # [win]
    - ninja  # [win]
    - perl  # [not win]
    - pkg-config
    - pthread-stubs  # [linux]
    - python >=3  # [not win]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cairo     # [build_platform != target_platform]
    - fribidi   # [build_platform != target_platform]
    - glib      # [build_platform != target_platform]
    - harfbuzz  # [build_platform != target_platform]
    - fontconfig  # [build_platform != target_platform]
    - freetype    # [build_platform != target_platform]
    - gobject-introspection  # [build_platform != target_platform]
    - libpng                 # [build_platform != target_platform]
  host:
    - cairo
    - fribidi
    - glib
    - harfbuzz  # [not win]
    # NOTE: harfbuzz installs everything that pango needs, but to avoid issues
    # with defaults we need to pin against conda-forge versions.
    - fontconfig  # [not win]
    - freetype  # [not win]
    - gobject-introspection
    - libpng
  run:
    - cairo
    - fribidi
    - harfbuzz  # [not win]
    - fontconfig  # [not win]
    - freetype  # [not win]
    - libpng

test:
  requires:
    - pkg-config
  commands:
    - pango-view --help

    # check that libraries are installed and can be found through pkg-config
    # (used by downstream builds)
    {% set libs = [
        "pango",
        "pangocairo",
    ] %}
    {% set libs = libs + ["pangoft2"] %}  # [unix]
    {% set libs = libs + ["pangowin32"] %}  # [win]
    {% for lib in libs %}
    - test -f $PREFIX/lib/lib{{ lib }}-1.0${SHLIB_EXT}  # [unix]
    - test -f `pkg-config --variable=libdir --dont-define-prefix {{ lib }}`/lib{{ lib }}-1.0${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\{{ lib }}-1.0-0.dll exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=exec_prefix --dont-define-prefix {{ lib }}`) do if not exist "%%a/bin/{{ lib }}-1.0-0.dll" exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ lib }}-1.0.lib exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=libdir --dont-define-prefix {{ lib }}`) do if not exist "%%a/{{ lib }}-1.0.lib" exit 1  # [win]
    {% endfor %}

about:
  home: http://www.pango.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: 'Text layout and rendering engine.'
  description: |
    Pango is a library for laying out and rendering of text, with an emphasis
    on internationalization. Pango can be used anywhere that text layout is
    needed, though most of the work on Pango so far has been done in the
    context of the GTK+ widget toolkit. Pango forms the core of text and font
    handling for GTK+-2.x.
  doc_url: http://www.pango.org/
  dev_url: https://gitlab.gnome.org/GNOME/pango

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
    - jakirkham
    - pkgw
